### ISSUE TITLE
Infill not sticking after board upgrade

### ISSUE THREAD

**Issue by SolorEclipse** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#101]
My infill isn't sticking after I upgraded to the skr pro v1.1 it's probably not the board it's probably something I've done any idea what could be causing this
![IMG_20200204_224739](https://user-images.githubusercontent.com/53887561/73995219-8d328900-491d-11ea-9878-f7f92f3ad75c.jpg)
![IMG_20200204_224745](https://user-images.githubusercontent.com/53887561/73995239-97548780-491d-11ea-851f-7117544aae05.jpg)

**Comment by oldman4U** [comment]
Hello SolorEclipse.

Seems this ticket is not in use anymore, so could you please close it.

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unneeded ticket. Thank you
