### ISSUE TITLE
Drv8825 drivers not recieving power

### ISSUE THREAD

**Issue by SrGeek** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#130]
I check vfer to adjust but there is no voltage across the driver, attached is a picture of the pins for MS1,MS2,MS3 and D.  Marlin setting changed drivers to drv8825.  need help thanks.  I checked VCC to ground and there is power.  However Vref does not have power and I cannot trip the drivers.  Since the Power out to the bed had the polarity reversed maybe there is something else in the circuit that needs to change.
![1EAF99CE-4723-4B85-A93E-538BF23A6FEB](https://user-images.githubusercontent.com/12385637/79608520-c8d69580-80ba-11ea-8ed6-f1971269c0fa.jpeg)

**Comment by SrGeek** [comment]
really guys nothing?

**Comment by oldman4U** [comment]
hi.

Have you see this guide made by an angel: https://github.com/GadgetAngel/SKR-PRO-V1.1-Stepper-Driver-Jumper-Configuration-Manual

Hope this helps

**Comment by SrGeek** [comment]
@oldman4U Yes that’s why I put the pics.  They match the document.  I haven't seen any one resolve this in any of the forums either.  !
Most give up and just wait on the TMC2209 or something similar.  Pretty disappointed

**Comment by oldman4U** [comment]
I had a similar problem with A4988 with green pcb. Finally i switched to
2209 with sensorless homing and i love them. You can only hear the noctua
fans and they are well known to be very very quiet.

Hope they will work for you like they do for me!😁

SrGeek <notifications@github.com> schrieb am Sa. 16. Mai 2020 um 07:50:

**Comment by oldman4U** [comment]
Hello SrGeek.

What is the status of the issue?

**Comment by SrGeek** [comment]
Still not resolved.  I got 2130 and 5160, I still cant get board to work.  Driver bad register problems.

**Comment by SrGeek** [comment]
Not working is a stretch.  I can heat the bed, turn on the LCD display, turn on fans...but drivers....silent stepper drivers are too silent because they dont turn on.

**Comment by SrGeek** [comment]
I have continuity between the power and ground pin of the motor power, once I changed the 15A fuse.  pretty frustrated.

**Comment by oldman4U** [comment]
So a broken fuse caused this issue? And you found the issue - this is great!

**Comment by SrGeek** [comment]
Motor power + and - are continuous.  My board is fried on all the driver sockets side.  Other than that everything else works, heaters, LCD etc.  My march order of SKR Pro boards never arrived (sad face) and Amazon doesn't sell them anymore.   So l am keeping the board stored somewhere maybe one day the PCB layout will become available and I will find what component  that got fried so I can solder in a new one.    Closing this issue.

**Comment by oldman4U** [comment]
Hi. Have tried to change the fuse ?

SrGeek <notifications@github.com> schrieb am Do. 18. Juni 2020 um 02:33:
