### ISSUE TITLE
Fan 0 ono more works ...

### ISSUE THREAD

**Issue by davidmarli** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#131]
I sould have done something wrong : the fan0 port osen't work anymore !!!
the led is not very bright. 
Only 4V comes out ...
Is there a fuse to change ? 
Fan 3 works well ...

Thank you for your help

**Comment by blondak** [comment]
Ho, do you solve this issue, it looks i have same one. Thanks

**Comment by davidmarli** [comment]
I didn't.
The first fan port is broken.
I use fan1 or fan2.

**Comment by blondak** [comment]
Thank you for your quick response, it looks, that this board quiet bad, I also have issues with endstops when using ESP,...
