### ISSUE TITLE
parts cooling fan control?

### ISSUE THREAD

**Issue by fenyx13** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#14]
I have hotend cooling on fan0 but when I have fans attached to fan 1 or 2 they don't start and I can't control them with m106.
thanks

**Comment by rlvanhuis** [comment]
@fenyx13, What were the steps used to solve.  I am at the same point.

Thanks

**Comment by fenyx13** [comment]
@rlvanhuis
I ended up using one of the sets of heater pins for the parts cooling fan and reassigning the pins in the firmware. Worked for me.

**Comment by rlvanhuis** [comment]
Not fully understanding how to trace the input to the output yet.  I hope
this is what you did to solve your issue.
I will remap the pins located in the file "pins_BIGRTEE_SKR_RRO_V1.1.h".  I
will swap PE5 for PD14.  If I follow correctly the output will move to the
heater 1 location?

Thanks

**Comment by fenyx13** [comment]
Yup, that’s what I did. Good luck! 🙂
