### ISSUE TITLE
.cursor file on SD card

### ISSUE THREAD

**Issue by outtacontrol216** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#150]
where can i download the original .cursor file which is on the SD card?

**Comment by oldman4U** [comment]
Hi outtacontrol216.

Why would you need the original firmware? I am sure this version is:
a. completely outdated and
b. will not work with your configuration, because it will unlikely fit your setup.

Please let us know, thank you

**Comment by oldman4U** [comment]
@outtacontrol216 

Are you still there???

**Comment by oldman4U** [comment]
Hi. Could you please be so kind and reply to my question or close this ticket in case you don’t need it anymore. 

Thank you

**Comment by oldman4U** [comment]
@outtacontrol216 

Close this ticket

**Comment by outtacontrol216** [comment]
yes, sorry and thank you!
