### ISSUE TITLE
MicroSD card reader no longer recognises any cards

### ISSUE THREAD

**Issue by Malaquitte** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#151]
Hi,

The micro SD port on the motherboard suddenly stopped working. The TFT35 screen displays the following message "Read onboard SDCard error". I tried a lot of different sdcards, with different format type, never mind. I am now completely stuck because I have no way to flash the firmware on my motherboard.

Any ideas are welcome...

**Comment by oldman4U** [comment]
So this happened after a firmware update?

**Comment by Malaquitte** [comment]
Maybe, to tell the truth, my last flash was a few days ago and since I use the TFT35 usb port to print, I didn't realize it immediately.

**Comment by oldman4U** [comment]
And firmware you can still upload?

Malaquitte <notifications@github.com> schrieb am So. 28. Juni 2020 um 10:16:

**Comment by Malaquitte** [comment]
none anymore, that's the problem. No matter what file I have on a card, the message is always the same.

**Comment by oldman4U** [comment]
Turn the printer off. Disconnect the TFT from the mainboard. Compile a firmware.bin file, copy it onto a SD card and insert the card into the SD card slot of the mainboard. Turn the printer on. Can you see the firmware update LED flash on the mainboard for approximately 10 seconds, before it stops flashing?

**Comment by Malaquitte** [comment]
It's perfect, I managed to flash my motherboard and by plugging my screen I can now flash again.
Thanks for the advice, I would never have thought to incriminate the screen...
That said, it's hard to understand it, sometimes the screen stays black under the Marlin interface after a flash, sometimes the .bin file is not deleted but I see the green led blinking!

**Comment by oldman4U** [comment]
So there is some improvement, that's great.

Please let me know in case there is anything else I can help you with. In case everything works fine, please help us to keep this system usable by closing this ticket

Thank you
