### ISSUE TITLE
SKR Pro v1.1 TMC2209v1.2 does not sensorless homing

### ISSUE THREAD

**Issue by Majestix1970** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#152]
Hi all,

I have a problem with my new SKR Pro v1.1 and my  TMC2209 v1.2 Driver.

The driver have been used fully functionally in my old SKR 1.4Turbo. After switching the board using the old Marlin 2.0.5.4 configuration sensorless homing stopped working because it does not move at all when doing G28. 
First I thought I need to readjust the sensitivity, but reducing it from the old values (x=130 y=190) to x=54 and y=100) it started to move but bumps hard into the end position with about 3 sec of making noise...
If I adjust the new values  eg. by +1 to X=55 it stops moving again... same for y. 
Then I thought it might be the TMC current. I changed it from the default Marlin value 800mA to 1100mA for all stepper drivers. Unfortunately did not help either.

Any ideas what the issue might be?
Printer is an cartasian Geeetech i3 Pro C Prusa clone.
Was working perfectly with the SKR1.4Turbo...
TMC2209 also work perfectly with the SKR1.4 Turbo.

Hope you can help.
Best regards
Majestix1970

**Comment by Majestix1970** [comment]
[Configuration_and_Configuration_adv.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/files/4842881/Configuration_and_Configuration_adv.zip)

**Comment by Majestix1970** [comment]
here are my .h files...

**Comment by Majestix1970** [comment]
sorry closed it unintentionally....

**Comment by oldman4U** [comment]
Hi.

I use the same board and driver and it works perfectly. I am sure we do not use the same motors and maybe also other factors are different, so there is not a lot to say - but it does work in general. I saw huge difference depending on the stiffness of the belts and i use 200mA for sensorless homing.

Hope this helps

**Comment by Majestix1970** [comment]
Hi oldman4u
Thanks for your reply...
My motors are simple NEMA17 driven with 24V
Belt strength I did check already 
and overall the exact same mechanical setting is working fine with the SKR 1.4 Turbo😂
I assume I got a faulty board.. Grrr

**Comment by oldman4U** [comment]
I have 2 SKRs in the meantime, one for testing and one in my printer;-)

So what are you going to do next?

**Comment by Majestix1970** [comment]
I am requesting an HW replacement of the SKR Pro 1.1 board
I do not see any issue with my configuration! 

The board is also behaving completly unpredictable. One time the same sensitivy setting makes the print bed hit hard the end position. Next time it does not move at all because it is too sensitive.

**Comment by oldman4U** [comment]
Sounds good and makes sense.

Last question. Are you using 12V or 24V and which power supply are you using?

**Comment by Majestix1970** [comment]
Hi 
I use 24V and a regulate switched Power supply with 15A. 

Why?

**Comment by oldman4U** [comment]
I saw some other tickets in the past, where a broken or cheap power supply also caused random issues.Maybe i can find some time to update to your Marlin version, which version are you using at the moment? 2.0.5 or the latest and greatest from GitHub?

**Comment by oldman4U** [comment]
Hi. Any news regarding the reported issue?

**Comment by oldman4U** [comment]
@Majestix1970 

Please close this ticket in case you do not need it anymore 

Thank you

**Comment by oldman4U** [comment]
Have you replaced the board in the meantime?

**Comment by Majestix1970** [comment]
Hi Oldman4U,
have returned the board and closed the ticket.
Thanks for your help

**Comment by oldman4U** [comment]
Perfect!

Hope you have more luck with another board.
