### ISSUE TITLE
Ymax endstop is not working

### ISSUE THREAD

**Issue by zacomposites** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#154]
hi guys. 

i am struggling to make y max endstop works. reason its ymax and not y min is because the y homing direction not right so i change it to 1, ive inverted everything on ymax endstop still when i check m119, nothing is triggered.

**Comment by oldman4U** [comment]
Hi. Which version of the firmware are you using?

**Comment by zacomposites** [comment]
Marlin bugfix 2.0.

**Comment by oldman4U** [comment]
And do you have physical endstops or are you using sensorless homing?

You may want to check this: https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/issues/103#issuecomment-599070627

**Comment by zacomposites** [comment]
I have physical endstop. Using 2208 driver uart. The board doesnt have +y
endstop like mks board etc. Does it mean i can only use min and not max?

**Comment by oldman4U** [comment]
Hi

I use senseless homing on min and software on max. Maybe you can change an unneeded endstop to be used as max, but i do not know. Have you tried to change the y endstop pins like described in the link i sent to you?

**Comment by zacomposites** [comment]
It Works!!! :) swap the Y min max value. Thanks !! 1 issue sorted. now my z axis doesnt want to move. all limit switch working fine. any idea?

**Comment by oldman4U** [comment]
I learned from the best. Gurmeet.

But the z axis moved before? Also 2208?

zacomposites <notifications@github.com> schrieb am So. 5. Juli 2020 um
22:17:

**Comment by oldman4U** [comment]
Just saw you closed the ticket. Seems all good. ;-)))

Thank you and happy printing

zacomposites <notifications@github.com> schrieb am So. 5. Juli 2020 um
22:17:

**Comment by zacomposites** [comment]
Hm.. before i compiled with cheetah from kay3d using similar build size
printer. Z axis does work.  Problem is that it uses 2 z motor..

My printer is the cr3040. It does have dual z ball screw but really its
just single motor with belt attached to both.

So..yeah.  now it doesn't want to work

**Comment by oldman4U** [comment]
So, please reopen your ticket or start a new one. This ticket is closed...

The SKR Pro v1.1 can be setup in Marlin using a single Z and you can simply remove the jumpers from the second z Axis and connect a motor there. It will move both motors automatically.

**Comment by AnHardt** [comment]
```cpp
//
// Limit Switches
//
#define X_MIN_PIN                           PB10
#define X_MAX_PIN                           PE15
#define Y_MIN_PIN                           PE12
#define Y_MAX_PIN                           PE10
#define Z_MIN_PIN                           PG8
#define Z_MAX_PIN                           PG5
```
When using 'endstop interrupts' `Y_MAX_PIN` (PE**10**) conflicts with `X_MIN_PIN` (PB**10**). The STM32 hardware allowes only one interrupt per end-**number**. All registers (A to J) share the same interrupt vector.

Either disable 'ENDSTOPINTERRUPTS' or swap Y_MAX_PIN with an other and connect the switch there.
