### ISSUE TITLE
BLTOUCH MARLIN 2.0 SKR PRO 1.1

### ISSUE THREAD

**Issue by adaly89** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#156]
Hi, how conect bltouch to skr?
When i connected in 4pin in board, and try auto level, i get error "stop called because of bltouch error restart with m999"
What need do for work?

**Comment by oldman4U** [comment]
Please see here for more information about 4pin vs. 5pin.

Hope this helps

**Comment by oldman4U** [comment]
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/issues/136

**Comment by oldman4U** [comment]
Hi.

Do you need any further information?

If not, please close this ticket.

Thank you

**Comment by oldman4U** [comment]
Hello @adaly89.

Please be so kind and close this ticket.

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by adaly89** [comment]
closed

**Comment by oldman4U** [comment]
Thank you

adaly89 <notifications@github.com> schrieb am So. 11. Okt. 2020 um 12:11:
