### ISSUE TITLE
 SKR PROv1.2 FYSETC TMC2209v3.0 by UART

### ISSUE THREAD

**Issue by Roman-ru** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#157]
Hello, how to connect UART FYSETC 2209v3.0 to SKR PROv1.2

**Comment by oldman4U** [comment]
Hi. Could you please check if this helps. https://github.com/GadgetAngel/SKR-PRO-V1.1-Stepper-Driver-Jumper-Configuration-Manual

**Comment by Roman-ru** [comment]
No, it doesn't help, there's no Fysetc 2209v3.0

**Comment by oldman4U** [comment]
Ok, sorry. In this case i can not help because i use btt tmc2209 with this
board.

I would recommend to use the bugfix Marlin from their github page and start
with the basic functions and add advanced features later on.

Hope someone uses the same stepper driver and can help.

Roman-ru <notifications@github.com> schrieb am So. 26. Juli 2020 um 07:46:

**Comment by Roman-ru** [comment]
Thank you anyway.

**Comment by oldman4U** [comment]
Make sure to desolder the diag pin in case you are not using sensorless homing  and set the jumpers on the mainboard for UART. Then you can set all other functions in software. Maybe you follow the BTT 2209 guideline from the document above and make sure the FYSTETC is setup for UART too.

**Comment by Roman121275** [comment]
Not working, no connection. Sending M122 connection error.

**Comment by oldman4U** [comment]
It is ANOTHER MAINBOARD but describes you driver:


https://3dwork.io/en/complete-guide-skr-v1-4-and-tmc2209

Roman121275 <notifications@github.com> schrieb am Mo. 27. Juli 2020 um
00:03:

**Comment by Roman121275** [comment]
Yes, I saw it, but I can't figure out where to put the jumper on my board

**Comment by oldman4U** [comment]
Hi.

Any news regarding the reported issue?

**Comment by Roman-ru** [comment]
Hello, there is nothing new, I ordered a Bigtreetech 2209 and will receive
it today.

вт, 4 авг. 2020 г., 04:51 oldman4U <notifications@github.com>:

**Comment by Roman121275** [comment]
Hello, there is nothing new, I ordered a Bigtreetech 2209 and will receive it today.
--
Отправлено из Mail.ru для Android вторник, 04 августа 2020г., 04:51 +09:00 от oldman4U  notifications@github.com :

**Comment by oldman4U** [comment]
This is great. Let me know how it works

**Comment by Roman-ru** [comment]
Work without problems

**Comment by oldman4U** [comment]
👍🏻

Roman-ru <notifications@github.com> schrieb am Mo. 10. Aug. 2020 um 16:22:

**Comment by markosko** [comment]
![Uploading 119476093_655038585156787_6097819317527174056_n.jpg…]()
In case someone have same problem with combination of SKR Pro and Fysetc TMC2209 v3.0, no need for soldering or cable wiring, uart jumper as normal, then another jumper on board between RX and TX lines, and under board jumper in middle row on left side as shown in image, M122 shows every connection ok.

**Comment by oldman4U** [comment]
👍🏻

@gadgetangel is this something for you?

**Comment by Roman-ru** [comment]
Yes,thank you!

вт, 15 сент. 2020 г., 18:14 oldman4U <notifications@github.com>:
