### ISSUE TITLE
bl touch m999 error skr mini e3 v2.0

### ISSUE THREAD

**Issue by jimthedinosuar** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#167]
Hello, I recently installed a bl touch version 3.1 on my ender 3 pro and while when the test worked fine when I went to auto bed level the m999 error came up. I tried rewiring it but that did not work it still brought up the m999 error I have looked at different git hub issues and tried them but nothing seems to work. Thank you if you have a solution

**Comment by oldman4U** [comment]
Hi.

This is the wrong repository for your mainboard.

Please close this ticket and start a new ticket here: https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues

Thank you

**Comment by jimthedinosuar** [comment]
Thank you @oldman4U

**Comment by oldman4U** [comment]
👍🏻

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
