### ISSUE TITLE
endstops not working after plugging in a driver (TMC2209)

### ISSUE THREAD

**Issue by outtacontrol216** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#169]
without a driver in the slot the endstop is working fine (red LED is ON and goes off when i trigger the endstop).
When i power off the board and plug in a TMC2009, the red LED is not ON and the endstop for this slot is not working anymore.
setup of the endstops are COM to ground and NC to Signal.
in marlin 2.0 endstop inverting is on false.

thank you for your help

**Comment by oldman4U** [comment]
Are you going to use sensor-less homing?
If not, have you removed the diagram pin from the 2209?

**Comment by outtacontrol216** [comment]
i am not going for sensor-less homing.
there is absolutely no difference when i remove the DIA pin of the TMC2209. 
as is said, the endstops are working and the red LED`s near the driver are ON only when there is no driver in the slot.

**Comment by outtacontrol216** [comment]
update: u cutted the wrong pin
https://github.com/bigtreetech/BIGTREETECH-TMC2209-V1.2/blob/master/TMC2209%20problems%20solving.pdf
helped me alot
thank you

**Comment by oldman4U** [comment]
👍🏻
