### ISSUE TITLE
Neopixel LED strip

### ISSUE THREAD

**Issue by outtacontrol216** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#170]
can you propose me a good choice for a pin for installing a Neopixel LED Strip?
which pins are PWM capable and free? 
SERVO0 (BLtouch) is in use.

thank you

**Comment by oldman4U** [comment]
Please check the other tickets before opening a new one. Maybe #158 could help.

Please help the community and close the ticket once you do not need it anymore. Thank you
