### ISSUE TITLE
Board not accepting firmware (skr pro v1.2)

### ISSUE THREAD

**Issue by quad121** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#172]
When trying to flash firmware to the board using the sd card and 'firmware.bin' file won't install to board.

**Comment by oldman4U** [comment]
Which firmware. Sd card size and format. Pictures. 

Please

**Comment by quad121** [comment]
I am trying to flash 'klipper' to the board using a Sandisk 32gb sd card, which has been formatted in the 'fat32' format (new card).

**Comment by quad121** [comment]
![image](https://user-images.githubusercontent.com/46540715/95576095-c466b600-0a27-11eb-93db-513faf451c26.jpeg)

**Comment by oldman4U** [comment]
I would use a card smaller 8GB for firmware flash, best the one which was included. Klipper I do not know. Sorry

**Comment by oldman4U** [comment]
But I would try it with the standard Marlin for a test of the hardware.

**Comment by quad121** [comment]
Many thanks for your time, I will try and flash the board with marlin and see how it goes.

**Comment by oldman4U** [comment]
Let me know.

Paul Harper <notifications@github.com> schrieb am Fr. 9. Okt. 2020 um 13:12:

**Comment by quad121** [comment]
I will.

**Comment by quad121** [comment]
O.K, I've downloaded the latest Marlin and configured and built using VS Code. 
The file still never got accepted!

**Comment by quad121** [comment]
I can't believe that a large manufacturing firm like Big TreeTech keep on supplying faulty goods?
I have had 2 skr 1.4 turbo mobo' s and both turned out to be faulty, as both had faulty mosfets on the part cooling fan output.

**Comment by oldman4U** [comment]
Can you zip you config and advanced and attach it here?

**Comment by oldman4U** [comment]
And use the sd card which came with the board.

You can rename the firmware file and try it directly with it.

**Comment by quad121** [comment]
[untitled folder.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/files/5355483/untitled.folder.zip)

This file was loosely configured, just to try to see if it would load!
I also did use the SD Card which came with the board

**Comment by quad121** [comment]
I also tried the BTT's Firmware also!!!

**Comment by quad121** [comment]
There also doesn't seem to be any lights lit either? Ive checked the fuses etc

**Comment by oldman4U** [comment]
Yes, please do so...

I mean you have connected almost everything possible, but you should start with the basics and add more stuff later on.

**Comment by quad121** [comment]
I've found this, I don't know if it will work but I suppose it's worth a go.

https://www.youtube.com/watch?v=7O_ZOdnM0SU&feature=youtu.be

**Comment by oldman4U** [comment]
Maybe you want to check if it takes power from USB first (check the jumper configuration) and also if the fuses are ok.

**Comment by quad121** [comment]
While waiting for the ST Link I thought I would connect the printer using Pronterface. Which it does connect! No function of the Axis though
![IMG_0056](https://user-images.githubusercontent.com/46540715/95653147-3b668200-0aee-11eb-8cb5-69d56f1509a0.jpg)

**Comment by quad121** [comment]
This must be firmware which was installed via the Company!

**Comment by quad121** [comment]
Ok, I've sorted the problem out and also have got the firmware to flash also

**Comment by dzervas** [comment]
but HOW did you solve it? @quad121

**Comment by afbenevides** [comment]
Hi, I would be interested in new solution ideas too if one has? I'm stuck with SKR pro 1.2 too not accepting firmware. Thanks, @dzervas @quad121

**Comment by afbenevides** [comment]
Thanks @quad121 the YouTube link + GitHub link did the trick for 2 of them... now I have to investigate the other 2 problem...

I put them here in case it helps someone else:

https://www.youtube.com/watch?v=7O_ZOdnM0SU
https://github.com/P-C-R/SKR_PRO_BOOTLOADER_REPAIR

**Comment by olijouve** [comment]
Hello @quad121, what was your issue that used to make the fuses blow immediately after replacing, and how did you fixed it ?
