### ISSUE TITLE
SKR Pro 1.2   If Limit switches are triggered, no movement response

### ISSUE THREAD

**Issue by evandene** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#180]
Symptom
When the board is fully wired, including BLTOUCH, the axis movements do not respond on triggered limit switches.
When limit switches are triggered, LED's along the stepper connectors do blink on/off accordantly.
When M119 executed all limit switches do stay triggered no matted if activated or not.
configuration files and PIN-file attached
Could somebody please help?
Thanks

[SKR_PRO_1_2.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/files/5582104/SKR_PRO_1_2.zip)

Board SKR Pro 1.2
Delta Printer
PCB limit switches used; VCC GND SIG
TMC2209 DIAG pins removed as advertised by BTT
Driver jumper set for UART (first pin duo)

**Comment by evandene** [comment]
Now for three days I was trying to make my DELTA printer to work with the TMC5160 in PSI mode but without luck.
The X-Y-Z movements are okay but the enstops do not work for a DELTA printer
A DELTA printer needs to home to MAX, and that simple doesn't work
No support from BIGTREETECH as always
What a waste of time and money

**Comment by evandene** [comment]
I have decided to scrap both my boards, the SKR PRO v1.1 and the SKR PRO v1.2
Both board have hardware flaws, and for both boards none or crappy support from Bigtreetech. Sad but lesson learned.

**Comment by oldman4U** [comment]
Have you checked #103?

**Comment by evandene** [comment]
Yep I did

**Comment by oldman4U** [comment]
Last try - 502/500 to clear ERPROM?

Ed van den Enden <notifications@github.com> schrieb am Di. 15. Dez. 2020 um
23:01:

**Comment by evandene** [comment]
SKR PRO v1.1 and v1.2 do not have an EEPROM but created a soft eeprom with enabling SDSUPPORT
After every new firmware installation one should always rum M502 and M500, and so I did.
Thanks for the good work, but the boards are scrapped now and I will move on with LERDGE K boards now.

**Comment by oldman4U** [comment]
Perfect. I own two of them.

Maybe you want to close this ticket once you don’t need it anymore.

Thank you

Ed van den Enden <notifications@github.com> schrieb am Mi. 16. Dez. 2020 um
08:42:

**Comment by oldman4U** [comment]
Thank you

Happy printing

Ed van den Enden <notifications@github.com> schrieb am Mi. 16. Dez. 2020 um
13:46:
