### ISSUE TITLE
Z height incorrect

### ISSUE THREAD

**Issue by TimListon** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#192]
I'm not sure where the right place to get assistance is so I'm starting here. If someone has a recommendation of somewhere else to go I'd appreciate that info as well.

I recently swapped out my board with a Bigtreetech SKR Pro 1.2 and a TFT E3 v3 display with my BLTouch. I've compiled Marlin 2.0 Bugfix and provided a link to the config files below.

[Configuration_adv.h.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/files/5852579/Configuration_adv.h.txt)
[Configuration.h.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/files/5852580/Configuration.h.txt)

The picture is the result of running the following commands:
G28
G28 Z
G1 F60 Z0

The problem is that whenever I home to Z0 the nozzle ends roughly 20-25mm off the build plate.
![Nozzle](https://user-images.githubusercontent.com/10439934/105423126-d0067300-5bf9-11eb-8bc5-e7a987f762e7.JPG)

I was able to create a mesh by disabling the steppers and moving the nozzle closer to the bed and then initiating a G29, but if I try to run G29 after G28 the process errors out because it is limited to traveling 20mm to find the build plate. I could increase this but it seems like it should be starting closer to the build plate to begin with.

Perhaps I'm not searching on the right terms to find the answer, but I've been trying to troubleshoot this for about 3 days (on and off).

**Comment by schnello** [comment]
Hi.

Take a look at:
#define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, **400**, 96 } // Customized TL

**Comment by TimListon** [comment]
I took a break for a while on this, but finally got back around to troubleshooting it.

It appears the problem ended up being that I needed to uncomment the following.
#define USE_PROBE_FOR_Z_HOMING //Customized TL

The printer is now homing correctly and generating its mesh without having to manually move the Z axis closer to the bed.
