### ISSUE TITLE
How do you setup Dual Z?

### ISSUE THREAD

**Issue by NovaViper** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#194]
Hey guys, im running Klipper on my SKR Pro, and Im trying to figure out how to setup Dual Z motors on the board.. my driver is a TMC2208 in UART mode

**Comment by oldman4U** [comment]
Using Marlin the firmware does not know about the second one because it is a feature of the hardware itself.

**Comment by Cheo7811** [comment]
oldman4U, Marling actually have a section for multiple stepper for Z, from 1 up to 4.

Line 576 in Marlin 2.0.7.2

#define NUM_Z_STEPPER_DRIVERS 1   // (1-4) Z options change based on how many

The question was, how to setup 2 on Klipper.

**Comment by oldman4U** [comment]
Maybe you should start a ticket in a Klipper forum then.

Most likely Klipper also has to be configured like a single Z because for
the firmware it works like a single Z.



Cheo7811 <notifications@github.com> schrieb am Do. 25. Feb. 2021 um 14:20:

**Comment by Cheo7811** [comment]
NovaViper:

There is a section for multiple steppers in the Klipper config, that should do the trick

https://www.klipper3d.org/Config_Reference.html#additional-stepper-motors-and-extruders

Perhaps that is enough for you to close this ticket

**Comment by NovaViper** [comment]
@Cheo7811 Thanks! I got it working and I found someone's config that does Dual Z on a SKR Pro
