### ISSUE TITLE
skr pro v1.1 board problems

### ISSUE THREAD

**Issue by SolorEclipse** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#26]
so i just bought an skr pro ver 1.1 right out the box i plugged it in and it installed the driver but the sd card didn't come up i could see the board in platform io but not the sd card same for the device manager all the lights on the board light up and the status light is solid green

like a dumb ass i removed the sd card put it in an adapter plugged it into my computer and formatted it little did i know there was a file called firmware.bin on it and i cant find a replacement now the board wont connect to the computer at all 

i believe this is my retarded moment for the week anyone know how to fix this or should i buy another board ?

**Comment by dant220** [comment]
You can compile another firmware.bin
