### ISSUE TITLE
Z Homeing not working

### ISSUE THREAD

**Issue by bmarl** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#34]
This happens with both the original Marlin 2.0 branch as well as this.
On sending G28 X1, X2 and Y  home fine, Z moves up, then down and triggers the endstop and just stops. Only after a reset Z move again and only on homing or if i set the Z position to something negative.
After exchanging Y/Z motor and endstop for a test i can rule out electrical problems.

**Comment by bmarl** [comment]
Just for clarification, i don't have BLTouch or similar activated.

**Comment by bmarl** [comment]
The issue seems to be the board itself. The same Marlin version works fine on the printer with the SKR 1.3

**Comment by oldman4U** [comment]
Hi bmarl.

Do we still need this ticket? If not, it would be great if you could close it.

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unneeded ticket. Thank you
