### ISSUE TITLE
Using USB CDC, TFT35 and ESP-01S at the same time

### ISSUE THREAD

**Issue by omahena** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#37]
How can we configure Marlin to allow a "triple head" configuration?

So that it is possible to use OctoPrint to control the board over the USB serial connection, the TFT35 when standing next to the printer and ESP-01S when we prefer it to OctoPrint?

**Comment by Evg33** [comment]
Marlin supports only 2 interfaces.

**Comment by omahena** [comment]
That seems evident from there being just two `SERIAL_PORT` and `SERIAL_PORT_2` defines in configuration.h...

@Evg33 Do you think... A third one might be easy to hack in? For STM32 platforms I couldn't find the "Serial.cpp" file implementation that specific platforms have.

@bigtreetech I wish this was mentioned on the buy pages for the LCD and WiFi module pages or even better - documentation. Maybe a compatibility matrix?

Does anyone need an ESP-01S board in the EU?

**Comment by dant220** [comment]
It is something I would be interested in too.

**Comment by omahena** [comment]
@dant220 I think I found a way... It includes sending more money to BTT... So... :/ But I think it is possible to get their TFT35 2.0 or 3.0 and it has a WiFi connector on the LCD board. Please verify all the details before you buy! So you connect Marlin to USB serial and Display serial and then the display will daisy chain the WiFi serial...
