### ISSUE TITLE
Anyone uses ENDSTOP_INTERRUPTS_FEATURE?

### ISSUE THREAD

**Issue by Haschtl** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#62]
I wonder if the endstop-pins are interrupt-capable.
I have enabled the ENDSTOP_INTERRUPTS_FEATURE, but my endstops are sometimes triggered strange (too hard). 
I wonder if this is due to the ENDSTOP_INTERRUPTS_FEATURE or just too high homing-speeds.

**Comment by ArtemKobz** [comment]
@Haschtl , did you find answer to your question?
I have exactly same question. 
According to datasheet for STM32F407 - all GPIO pins are interrupt capable, so the question is - if it is implemented in software.
