### ISSUE TITLE
Activate StealthChop with TMC2209

### ISSUE THREAD

**Issue by curvi** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#64]
I am compiling for my new SKR Pro v1.1 board, which by now does not have any motors attached, but I have drivers for X,Y,Z,E0 installed. I've plugged the 4 TMC 2209 drivers, with cut Stallguard pins, into the headers and put in the UART jumpers.
I activated `#define MONITOR_DRIVER_STATUS` and `#define TMC_DEBUG`.
I compiled the code and put the firmware.bin alongside the FIRMWARE.cur on the sd card and it runs. I can change the maximum current per driver, as I see using a M122 commad via pronterface. However the full response is:

```
M122
SENDING:M122
		X	Y	Z	E
Address		0	0	0	0
Enabled		false	false	false	false
Set current	780	780	780	950
RMS current	1381	1381	1381	939
MAX current	1947	1947	1947	1324
Run current	24/31	24/31	24/31	16/31
Hold current	12/31	12/31	12/31	8/31
CS actual	0/31	0/31	0/31	0/31
PWM scale	0	0	0	0
vsense		0=.325	0=.325	0=.325	0=.325
stealthChop	false	false	false	false
msteps		256	256	256	256
tstep		0	0	0	0
pwm
threshold
[mm/s]
OT prewarn	false	false	false	false
OT prewarn has
been triggered	false	false	false	false
off time	0	0	0	0
blank time	16	16	16	16
hysteresis
-end		-3	-3	-3	-3
-start		1	1	1	1
Stallguard thrs	0	0	0	0
DRVSTATUS	X	Y	Z	E
stst
olb
ola
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:
		X	0x00:00:00:00	 Bad response!
		Y	0x00:00:00:00	 Bad response!
		Z	0x00:00:00:00	 Bad response!
		E	0x00:00:00:00	 Bad response!
Testing X connection... Error: All LOW
Testing Y connection... Error: All LOW
Testing Z connection... Error: All LOW
Testing E connection... Error: All LOW
```
The connection is ALL LOW, sure, because no motor is attached and I'm running on USB power. But stealthChop is false for all axes. Is this a expected response? I can change the set current individually, but not this entry!

I also tried
```
#define STEALTHCHOP_XY
#define STEALTHCHOP_Z
//#define STEALTHCHOP_E
```
and still, all responses are false.
The expected response would be a driver register code and stealthchop for the specified axes.
Am I doing something wrong?
I've attached the 
[configuration.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/files/3776047/configuration.zip)

**Comment by AnyM2k** [comment]
USB is wrong. Connect 12-24V(to motors too). Read more info. 2209 soldered ? RX-TX ?
