### ISSUE TITLE
schematics

### ISSUE THREAD

**Issue by dobryj** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#7]
Can you publish also schematics?
PINout it not suficient for all questions. For example board use independent power source for different purposes. But is is not clear which power source (and voltage) is used for FANs. I thing, that this powers have common ground, but it is not clear. And many other questions like this.

Thanks

**Comment by Msq001** [comment]
hello, sch is uploaded [here](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/blob/master/Schematic/SKR-PRO-V1.1%EF%BC%88SCH%EF%BC%89.pdf)

**Comment by dobryj** [comment]
Thanks!
For me is surprise, that FANs using power source same as head heaters, not board power line.
