### ISSUE TITLE
CPU some how is dead. Changed. Board is on but no usb or sd read.

### ISSUE THREAD

**Issue by AnyM2k** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#72]
CPU some how is dead. Changed. Board is on but no usb or sd read.
Any help ? What and how write to new cpu ? Red light is on . Blue light SD card on if connected. 
All endstops is on.

Thank you.

**Comment by holgin** [comment]
You need to flash the bootloader to the MCU with ST-LINK. Im trying to do it now, I will let you know if I succeed.

**Comment by AnyM2k** [comment]
Thank you for quick answer ! 
May be you have link where to buy and how to use(checked) ? 

Thank you very much !

**Comment by rflulling** [comment]
do you have the jumper for the USB / 5V power set? Do you have power set right to each of the supply lines? There are 3 supply lines. Plus USB supply if enabled.

**Comment by Baltazart** [comment]
If you need a SKR-Pro v1.1 bootloader, there is a dropbox link, bootloader TFT35v3.0 and SKR-Pro v1.1 to load with STM32CubeProgrammer, USB ST LINK v2 on the SWD connector of SKR-PRO .
https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/issues/20

**Comment by AnyM2k** [comment]
Leds for all 3 power lines on. on usb only 2 on 5V and 3.3V .
Thank you for bootloader ! Ordered ST-Link v2 ... waiting.

**Comment by holgin** [comment]
I have used this bootlader and STM32 ST-LINK Utility to upload it and it works, the board is alive :)
[fw_stlink.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/files/3908434/fw_stlink.zip)

**Comment by AnyM2k** [comment]
Have st-link V2 on table. At last. 
Any idea how to connect it to SKR-Pro-v1.1 ? 
Soldering to legs ?  Any other ways ? 
Thank you.

**Comment by AnyM2k** [comment]
Have some one step by step howto ?
Too many pins , to many errors may occur .

Thank you.

**Comment by GadgetAngel** [comment]
Can I use the STM32CubeProgrammer, USB ST LINK v2 on the SWD connector of SKR-PRO to burn a bootloader to the SKR PRO board so I can upload firmware to the board through the USB connection?

**Comment by Nyxtegida** [comment]
I received mine with problems, at first it connected to serial but didn't respond to any commands through pronterface. Nor did any difference after trying another firmware in the sd card. Later it didn't even show as a serial but did a read with the st-link. I tried flashing the bootloader from stm32cubeProgrammer, it shown download complete, but didn't confirm the write. After that, reading the mcu gives me full FFFF. Great! XD

**Comment by AnyM2k** [comment]
It alive. 
Thank you holgin for fw_stlink file. Connect USB ST LINK v2 to SWD connector of SKR-PRO , ignore reset pin. I use STM32 ST-LINK utility. Open fw , write. 
Thank you.
