### ISSUE TITLE
Stepper Drivers TMC5160 ver1.3 is not working in SPI or URTA Mode on BIGTREETECH-SKR-PRO-V1.1 Board

### ISSUE THREAD

**Issue by georgev1456** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#76]
Bought the BIGTREETECH-SKR-PRO-V1.1 Board w/ TMC5160 ver1.3 Drivers. 
I cant get it to work, i have tired everything , switching jumpers in SPI Mode or URTA, edited Marlin the Configuration.h , Configuration_adv.h, platformio.ini  i get problems when i change CS Pins  in the Marlin \src \pins directory file "pins_BTT_SKR_PRO_V1_1.h"  i cant build firmware the error come  
on.
 Also i have problem with USB Port , i cant connect it to my computer, I see red light on, but no com port available on my PC .
https://youtu.be/yBzPaFKoo_o
 

![20191211_023135](https://user-images.githubusercontent.com/47779112/70614816-151b4180-1bc0-11ea-9df8-0e0afac485e3.jpg)

![20191211_023141](https://user-images.githubusercontent.com/47779112/70614817-151b4180-1bc0-11ea-8120-e042a4ff377c.jpg)

![20191211_023207](https://user-images.githubusercontent.com/47779112/70614818-151b4180-1bc0-11ea-9689-65fab1c9917c.jpg)

i used this manual for steppers.
 https://github.com/bigtreetech/BIGTREETECH-TMC5160-V1.0/blob/master/manual/BIGTREETECH%20TMC5160-V1.0%20manual.pdf

![configuration steppers](https://user-images.githubusercontent.com/47779112/70613678-e9975780-1bbd-11ea-83ec-a8232f8222f3.JPG)

![configuration](https://user-images.githubusercontent.com/47779112/70613679-e9975780-1bbd-11ea-9241-9ac8d821b4ab.JPG)

![pins](https://user-images.githubusercontent.com/47779112/70613681-e9975780-1bbd-11ea-8871-8ea9177f9030.JPG)

 

NEED HELP......................

**Comment by oldman4U** [comment]
Hi george.

I believe you have to use "TMC5160_STANDALONE" with the jumpers set like shown especially on the second picture.

Georg

**Comment by oldman4U** [comment]
Sorry, you are using SPI mode, so the jumpers should be fine.....

I write this instead of deleting the message above. Because i use 2209 in UART mode successfully, but had a similar issue using A4988, i believed i could help, but i have no experience with SPI and 5160, so sorry for the confusion.

**Comment by wesk-ms** [comment]
Post both of your configuration files and someone might be able to help.

**Comment by dineshvyas** [comment]
there are lots of changes to be made. compare my configration_adv.h with yours
[Configuration_adv.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/files/3973672/Configuration_adv.zip)
working configration_adv.h
![CaptureTMC DEBUG](https://user-images.githubusercontent.com/55104840/71003114-944fce80-2106-11ea-94d0-fe741f87f7eb.JPG)

**Comment by dineshvyas** [comment]
sorry I did't know it was for TMC5160 v1.3
mine are TMC5160 v1.2

**Comment by georgev1456** [comment]
so the problem was in the BIGTREETECH-SKR-PRO-V1.1 board , i have received board replacement , now everything works.
![WIN_20191225_21_48_11_Pro](https://user-images.githubusercontent.com/47779112/71460408-9813ce80-2760-11ea-97e8-939bab8644b2.jpg)
[MARLINE CODE FOR TMC5160.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/files/4001516/MARLINE.CODE.FOR.TMC5160.zip)
