### ISSUE TITLE
Temprature Reading Incorrect For Bed and Hotend

### ISSUE THREAD

**Issue by MrLAtt** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#79]
After a few issues, I've managed to get my SKR Pro V1.1 working, but still with one problem.

The temprature reading for both the Heat bed and the Hotend are incorrect, I have selected the correct temp sensor (#5, ATC Semitec 104GT-2) and this setup was working perfectly before on my ramps 1.4 board and reading accurate temps.

The reported temprature never goes below 60*c (as on display and in pronterface) even when both the bed and the hotend are at ambient temprature, but once the temprature reaches 60*c its seems to be reported reasonably accurately (only 5-10*c off, as measuresd with an IR Temp sensor).

I have somewhat been able to solve this problem by adding a 1k resistor between the temprature sense pins and 5v, but it still displays 35*c at ambient, and now my temprature readings at higher tempratures are inacurate.

Has anyone else had this problem?

**Comment by oldman4U** [comment]
Hello MrLAtt.

Seems this ticket has not been used for a while, so i ask you to close it.

Thank you
