### ISSUE TITLE
Serial 3 Error

### ISSUE THREAD

**Issue by akarnaukh** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#86]
When I want to select serial 3, a link error occurs.
#define SERIAL_PORT 1
#define SERIAL_PORT_2 3

Linking .pio/build/BIGTREE_SKR_PRO/firmware.elf
.pio/build/BIGTREE_SKR_PRO/src/src/Marlin.cpp.o: In function `manage_inactivity(bool)':
/Users/akarnaukh/SKR_PRO/Marlin/Marlin/src/Marlin.cpp:483: undefined reference to `Serial3'
.pio/build/BIGTREE_SKR_PRO/src/src/Marlin.cpp.o: In function `setup':
/Users/akarnaukh/SKR_PRO/Marlin/Marlin/src/Marlin.cpp:1120: undefined reference to `Serial3'
.pio/build/BIGTREE_SKR_PRO/src/src/core/serial.cpp.o: In function `serialprintPGM(char const*)':
/Users/akarnaukh/SKR_PRO/Marlin/Marlin/src/core/serial.cpp:37: undefined reference to `Serial3'
.pio/build/BIGTREE_SKR_PRO/src/src/core/serial.cpp.o: In function `serial_echopair_PGM(char const*, char const*)':
/Users/akarnaukh/SKR_PRO/Marlin/Marlin/src/core/serial.cpp:41: undefined reference to `Serial3'
.pio/build/BIGTREE_SKR_PRO/src/src/core/serial.cpp.o: In function `serial_echopair_PGM(char const*, int)':
/Users/akarnaukh/SKR_PRO/Marlin/Marlin/src/core/serial.cpp:43: undefined reference to `Serial3'
.pio/build/BIGTREE_SKR_PRO/src/src/core/serial.cpp.o:/Users/akarnaukh/SKR_PRO/Marlin/Marlin/src/core/serial.cpp:44: more undefined references to `Serial3' follow

While switched to Serial 6. 
But it's inconvenient, how do I fix it?

**Comment by oldman4U** [comment]
Hello akarnaukh.

What kind of hardware would you like to connect to serial 3? As far as i know, the following Serials can be used with the SKR Pro v1.1:

SKR PRO v1.1
Serial port:
-1 is for USB
1 is for TFT
6 is for ESP-01S

Please let me know

**Comment by akarnaukh** [comment]
oldman4U 
to connect SonnOff instead of esp.
All the ports you have listed are just serial ports that are no different from each other. Except maybe USB.
There is no difference what to connect to them. Now for example I use the TTF port to connect to the computer.
The Board has a divorced serial3 port, it should work

**Comment by oldman4U** [comment]
OK. Sorry, but i can not help in this case.

**Comment by oldman4U** [comment]
Hello akarnaukh.

Seems this ticket has not been used for a while, so it would be great if you could close it.

Thank you

**Comment by oldman4U** [comment]
@bigtreetech Could you please close this unneeded ticket. Thank you
