### ISSUE TITLE
Not an issue, just a question on connectors

### ISSUE THREAD

**Issue by jimhiggs** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#90]
What connector type is needed for the stepper motor sockets? I am using std dupont and am having problems with dodgy connections (are pins too short for duponts?)

**Comment by theopensourcerer** [comment]
This image makes it look like they are JST XH 4 pin:

https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/blob/master/picture/SKR%20PRO%20V1.1-TOP.png

**Comment by jimhiggs** [comment]
Thnks I will get some on order.

**Comment by i-make-robots** [comment]
So, @jimhiggs, was it the correct connector? I'm facing the same issue right now.
